spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  data:
    mongodb:
      database: ${MONGODB_DBNAME}
      uri: ${MONGODB_URI}
#  profiles:
#    include: 
#    - swaggerEN

#logging
logging:
  level:
    org.springframework.data: ${LOG_LEVEL_SPRING_DATA:debug}

app:
  rest-client:
    one-trust:
      service:
        name: one-trust
        privacy-notices:
          base-url: ${ONE_TRUST_PRIVACYNOTICES_BASE_URL:https://api-io.dev.cstar.pagopa.it/idpay/mock/api/privacynotice/v2}
          tosId: ${ONE_TRUST_TOS_ID:123}
          apiKey: ${IO_BACKEND_SERVICE_SUBSCRIPTION_API_KEY:fake-api-key}

#Management Actuator
management:
  endpoints:
    web:
      exposure:
        include: info, health