spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  data:
    mongodb:
      database: ${MONGODB_DBNAME}
      uri: ${MONGODB_URI}

app:
  rest-client:
    one-trust:
      service:
        name: one-trust
        privacy-notices:
          base-url: ${ONE_TRUST_PRIVACYNOTICES_BASE_URL:https://api-io.dev.cstar.pagopa.it/idpay/mock/api/privacynotice/v2}
          tosId: ${ONE_TRUST_TOS_ID:123}
          apiKey: ${IO_BACKEND_SERVICE_SUBSCRIPTION_API_KEY:fake-api-key}

#Management Actuator
management:
  endpoints:
    web:
      exposure:
        include: info, health

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    it.gov.pagopa: ${LOG_LEVEL_PAGOPA:INFO}
    org.springframework.data: ${LOG_LEVEL_SPRING_DATA:INFO}
    org.springframework.boot: ${LOG_LEVEL_SPRING_BOOT:INFO}
    io.swagger: ${LOG_LEVEL_IO_SWAGGER:WARN}
    javax.persistence: ${LOG_LEVEL_JAVAX_PERSISTENCE:INFO}
    org.hibernate: ${LOG_LEVEL_ORG_HIBERNATE:INFO}
    org.mongodb.driver: ${LOG_LEVEL_MONGODB_DRIVER:WARN}