apiVersion: v2
name: idpay-portal-welfare-backend-role-permission
description: Welfare Portal for IdPay
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"