microservice-chart:
  namespace: "idpay"
  nameOverride: ""
  fullnameOverride: ""

  image:
    repository: cstarucommonacr.azurecr.io/idpayportalwelfarebackendrolepermission
    tag: latest
    pullPolicy: Always

  ingress:
    host: "uat01.idpay.internal.uat.cstar.pagopa.it"

  resources:
    requests:
      memory: "256Mi"
      cpu: "40m"
    limits:
      memory: "1Gi"
      cpu: "200m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envSecret:
    aks-api-url: cstar-u-weu-uat01-aks-apiserver-url
#    ONETRUST_TOS_ID: TODO

  keyvault:
    name: "cstar-u-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

#  envConfig:
#    ONETRUST_PRIVACYNOTICES_URL: TODO

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
