microservice-chart:
  namespace: "idpay"
  nameOverride: ""
  fullnameOverride: ""


  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 8080

  ingress:
    create: true
    path: /idpayportalwelfarebackendrolepermission/(.*)

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false

#  autoscaling:
#    enable: true
#    minReplica: 1
#    maxReplica: 2
#    pollingInterval: 30 # seconds
#    cooldownPeriod: 300 # seconds
#    triggers:
#      - type: azure-monitor
#        metadata:
#          tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
#          subscriptionId: ac17914c-79bf-48fa-831e-1359ef74c1d5
#          resourceGroupName: dvopla-d-sec-rg
#          resourceURI: Microsoft.KeyVault/vaults/dvopla-d-neu-kv
#          metricName: ServiceApiHit
#          # metricNamespace: Microsoft.KeyVault/vaults
#          # metricFilter: namespace eq 'default'
#          # metricAggregationInterval: "-1:1:0"
#          metricAggregationType: Count
#          targetValue: "30"

  envConfig:
    MONGODB_DBNAME: idpay

  envSecret:
    MONGODB_URI: mongodb-connection-string


  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
